CREATE DATABASE stock;
CREATE TABLE IF NOT EXISTS stock (
  id INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code INT(12) NOT NULL,
  name TEXT NOT NULL,
  amount TEXT NOT NULL,
  proportion TEXT NOT NULL,
  dateT TEXT NOT NULL,
  city_code INT(12) NOT NULL,
  update_state INT(1) NOT NULL
) DEFAULT CHARACTER SET gbk COLLATE gbk_chinese_ci;